{
 "title": "Receipt Processor Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Bytes allocated in heap and currently in use (Gauge)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "mem" }
   ]
  },
  {
   "title": "Total HTTP Requests (Counter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "receipt_processor_http_requests_received_total",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(receipt_processor_http_requests_received_total{}[1m])",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "HTTP Responses by status (Counter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "receipt_processor_http_responses_sent_by_status_total{status_code=\"200\"}",
     "legendFormat": "200"
    },
    {
     "expr": "receipt_processor_http_responses_sent_by_status_total{status_code=\"201\"}",
     "legendFormat": "201"
    },
    {
     "expr": "receipt_processor_http_responses_sent_by_status_total{status_code=\"404\"}",
     "legendFormat": "404"
    },
    {
     "expr": "receipt_processor_http_responses_sent_by_status_total{status_code=\"500\"}",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Total HTTP Responses (Counter)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "receipt_processor_http_responses_sent_total",
     "legendFormat": "responses"
    }
   ]
  },
  {
   "title": "Item count (Counter)",
   "type": "timeseries",
   "description": "Number of items created",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "receipt_processor_item_count", "legendFormat": "items" }
   ]
  },
  {
   "title": "Latency (Histogram)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(receipt_processor_http_response_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(receipt_processor_http_response_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(receipt_processor_http_response_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Receipt count (Counter)",
   "type": "timeseries",
   "description": "Number of receipts created",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "receipt_processor_receipt_count",
     "legendFormat": "receipts"
    }
   ]
  }
 ]
}